# docker-compose.yml - Composition of micro-services to run scaled cars software.
# Copyright (C) 2016 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2016-10-08

version: '2'

services:
    odsupercomponent:
        build: .
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"


    # micro service for proxy-fh16.
    proxy-fh16:
        build: .
        network_mode: "host"
        devices:
        - "/dev/pcanpci32:/dev/pcan32"
        depends_on:
            - odsupercomponent
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-fh16 --cid=${CID} --freq=100"


    # micro service for proxy-trimble.
    proxy-trimble:
        build: .
        network_mode: "host"
        depends_on:
            - odsupercomponent
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-trimble --cid=${CID}"


    # microservice for opendlv-legacy-simpledriver
    # docker run -ti --rm=true --net=host -v $PWD:/opt/opendlv.data -w /opt/opendlv.data seresearch/opendlv-on-opendlv-core-on-opendavinci-ubuntu-16.04-complete:latest /opt/opendlv/bin/opendlv-legacy-simpledriver --cid=189 --freq=10
    opendlv-legacy-simpledriver:
        build: .
        network_mode: "host"
        depends_on:
            - odsupercomponent
        volumes:
        - .:/opt/opendlv.data
        working_dir: "/opt/opendlv.data"
        command: "/opt/opendlv/bin/opendlv-legacy-simpledriver --cid=${CID} --freq=10"

